name: create pip-glibc Docker image

on:

  workflow_dispatch:

    inputs:

      distros:
        description: 'distribtions to create the images'
        required: true
        default: 'centos7,centos8'

      archtypes:
        description: 'architecture types of the images'
        required: true
        default: 'multiarch,amd64,arm64'

jobs:

  dispatch:

    runs-on: ubuntu-latest

    steps:

      - name: convert distros/archtypes strings to arrays
        id: to_array
        run: |
           echo "::set-output name=distros::[$(echo "${{ github.event.inputs.distros }}" | awk -F, '{printf "\"%s\"", $1; for (i=2; i<=NF; i++) printf ", \"%s\"", $i; }')]"
           echo "::set-output name=archtypes::[$(echo "${{ github.event.inputs.archtypes }}" | awk -F, '{printf "\"%s\"", $1; for (i=2; i<=NF; i++) printf ", \"%s\"", $i; }')]"

      - name: debug print
        run: |
           echo "github.event.inputs.distros=<${{ github.event.inputs.distros }}>"
           echo "github.event.inputs.archtypes=<${{ github.event.inputs.archtypes }}>"
           echo "steps.to_array.outputs.distros=<${{ steps.to_array.outputs.distros }}>"
           echo "steps.to_array.outputs.archtypes=<${{ steps.to_array.outputs.archtypes }}>"

      - name: dispatch event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PIP_BUILD_TOKEN }}
          repository: ${{ github.repository }}
          event-type: pip-glibc-rpm-built
          client-payload: '{ "distros": ${{ steps.to_array.outputs.distros }}, "archtypes": ${{ steps.to_array.outputs.archtypes }} }'
